global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-weather-batch'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080'] # 로컬에서 SpringBoot 실행 + Docker로 prometheus, grafana 실행 기준
