spring:
  application:
    name: sb01-otboo-team05
  profiles:
    active: default
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

# 로깅 레벨 설정
logging:
  level:
    root: info
    org.hibernate.SQL: debug

# 액츄에이터
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, loggers
  info:
    env:
      enabled: true