name: build .jar file

#on:
#  pull_request:
#    types:
#      - closed
#    branches:
#      - main
#      - develop

on:
  push:
    branches:
      - 'ci#68'  # 테스트 브랜치에서만 실행

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build .jar file with Gradle
        run: ./gradlew build -x test

      - name: Extract build metadata
        id: meta
        run: |
          echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          echo "build_date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Prepare Docker context
        run: |
          mkdir docker-context
          JAR_PATH=$(ls -1 build/libs/*.jar | head -n 1)
          echo "📦 Found JAR: $JAR_PATH"
          cp "$JAR_PATH" docker-context/app.jar
          cp Dockerfile docker-context/
          echo "📂 docker-context contents:"
          ls -al docker-context/

      - name: Buildah Build
        uses: redhat-actions/buildah-build@v2.13
        with:
          image: ootd_image
          tags: |
            latest
            pr-${{ steps.meta.outputs.pr_number }}
            sha-${{ steps.meta.outputs.sha_short }}
            date-${{ steps.meta.outputs.build_date }}
          dockerfiles: |
            ./docker-context/Dockerfile
          context: ./docker-context
          layers: true
          tls-verify: true
