name: build .jar file

on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - develop

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build .jar file with Gradle
        run: ./gradlew build -x test

      - name: Extract build metadata
        id: meta
        run: |
          echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          echo "build_date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Buildah Build
        uses: redhat-actions/buildah-build@v2.13
        with:
          image: ootd_image
          tags: |
            latest
            pr-${{ steps.meta.outputs.pr_number }}
            sha-${{ steps.meta.outputs.sha_short }}
            date-${{ steps.meta.outputs.build_date }}
          dockerfiles: |
            ./Dockerfile
          context: .
          content: |
            build/libs/sb01otbooteam05-0.0.1-SNAPSHOT.jar
          layers: true
          tls-verify: true